// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgDperrtprIFnPtoTCuLnYuxPpqQ6ytcI',
    appId: '1:74575195502:web:72689f56d7cb6cec8fe57f',
    messagingSenderId: '74575195502',
    projectId: 'room-automation-a1ce8',
    authDomain: 'room-automation-a1ce8.firebaseapp.com',
    databaseURL: 'https://room-automation-a1ce8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'room-automation-a1ce8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBULljv4890D4di3GYAjt0dd2dd9hUS2ok',
    appId: '1:74575195502:android:ebd97cc16ce242478fe57f',
    messagingSenderId: '74575195502',
    projectId: 'room-automation-a1ce8',
    databaseURL: 'https://room-automation-a1ce8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'room-automation-a1ce8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnwDCSkLj0_ym9VTEWVpd96ulsaG6w9WU',
    appId: '1:74575195502:ios:59854c2056bc155e8fe57f',
    messagingSenderId: '74575195502',
    projectId: 'room-automation-a1ce8',
    databaseURL: 'https://room-automation-a1ce8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'room-automation-a1ce8.appspot.com',
    iosBundleId: 'com.example.roomAutomation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnwDCSkLj0_ym9VTEWVpd96ulsaG6w9WU',
    appId: '1:74575195502:ios:ddff52294b64334c8fe57f',
    messagingSenderId: '74575195502',
    projectId: 'room-automation-a1ce8',
    databaseURL: 'https://room-automation-a1ce8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'room-automation-a1ce8.appspot.com',
    iosBundleId: 'com.example.roomAutomation.RunnerTests',
  );
}
